version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - superheroes-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hero
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=superheroes
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  superheroes-db: