server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/superheroes
    username: hero
    password: 1234
    hikari:
      schema: superheroes
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: hero
    password: 1234

db:
  flyway:
    clean: true
